version: '3.3'

networks:
  panel:
    driver: bridge

services:
  panel_db:
    container_name: panel_db
    image: mysql:8
    ports:
      - 13307:3306
    volumes:
      - ./docker/db/storage:/var/lib/mysql
      - ./docker/db/backup:/var/db
      - ./docker/db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: panel
      MYSQL_USER: developer
    networks:
      - panel


